/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.project.hotel.management;

import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author Cpt.coldblood
 */
public class Newpwd extends javax.swing.JFrame {

    /**
     * Creates new form Newpwd
     */
    public Newpwd() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ic.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        txtCnew = new javax.swing.JPasswordField();
        txtNew = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtUid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reset Password");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reset  Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 19, 218, 42));

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel2.setText("New Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 74, 152, 40));

        jLabel3.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel3.setText("Confirm New Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 139, -1, 40));

        btnConfirm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnConfirm.setText("Confirm and Login");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 225, -1, 42));

        txtCnew.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCnew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCnewKeyPressed(evt);
            }
        });
        getContentPane().add(txtCnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 137, 236, 48));

        txtNew.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewKeyPressed(evt);
            }
        });
        getContentPane().add(txtNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 236, 45));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/hotel/management/lock.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 130, 280, 200));
        getContentPane().add(txtUid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
       String newp,cnewp,uid;
       uid=txtUid.getText();
       newp=txtNew.getText();
       cnewp=txtCnew.getText();
       boolean valid=ValidatePassword.checkPwd(newp);
       if(newp.isEmpty()||cnewp.isEmpty()){
           JOptionPane.showMessageDialog(rootPane, "Please enter a Password", "Empty", ERROR_MESSAGE);
       }
       
       else if(ValidatePassword.specialCheck(newp)==false||ValidatePassword.chckchar(newp)==false){
           JOptionPane.showMessageDialog(null,"Password Must contain atleast each of an uppercase letter,a lowercase letter,a number and symbol","Weak Password",JOptionPane.ERROR_MESSAGE);
       }
       else if(newp.equals(cnewp)){
       DBConnect con=new DBConnect();
       Connection c=con.connect();
       try{
           Statement s1=c.createStatement();
           int y=s1.executeUpdate("update signup set password='"+newp+"' where uid='"+uid+"'");
           
       }
       catch(SQLException e){
           System.out.print(e.getMessage());
       }
       Login l=new Login();
       l.setVisible(true);
       this.setVisible(false);
       }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void txtNewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewKeyPressed
        char c=evt.getKeyChar();
        if(Character.isWhitespace(c)){
            txtNew.setEditable(false);
        }
        else{
            txtNew.setEditable(true);
        }
    }//GEN-LAST:event_txtNewKeyPressed

    private void txtCnewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCnewKeyPressed
        char c=evt.getKeyChar();
        if(Character.isWhitespace(c)){
            txtCnew.setEditable(false);
        }
        else{
            txtCnew.setEditable(true);
        }
    }//GEN-LAST:event_txtCnewKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Newpwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Newpwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Newpwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Newpwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Newpwd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtCnew;
    private javax.swing.JPasswordField txtNew;
    public static javax.swing.JLabel txtUid;
    // End of variables declaration//GEN-END:variables
}
