/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.project.hotel.management;
import java.awt.Toolkit;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
/**
 *
 * @author Cpt.coldblood
 */
public class PwdBackup extends javax.swing.JFrame {

    /**
     * Creates new form PwdBackup
     */
    public PwdBackup() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ic.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbQ1 = new javax.swing.JComboBox();
        cmbQ2 = new javax.swing.JComboBox();
        txtAns1 = new javax.swing.JTextField();
        txtAns2 = new javax.swing.JTextField();
        txtUid = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnClr = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Back Up Password and Set Up Recovery");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Set Up Password Recovery");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 42));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setText("User ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 68, 67, 34));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 115, 67, 34));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setText("Question 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 162, -1, 34));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setText("Question 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 256, -1, 34));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setText("Answer 1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 209, 67, 34));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setText("Answer 2");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 303, 67, 34));

        cmbQ1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        cmbQ1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "When did you Start working Here?", "What was the name of your 3rd Grade teacher?", "In what Year did your Parents Get married?", "Where was your first place of work?", "Who was your first crush?", " " }));
        getContentPane().add(cmbQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 162, 511, 34));

        cmbQ2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        cmbQ2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "When did you Start working Here?", "What was the name of your 3rd Grade teacher?", "In what Year did your Parents Get married?", "Where was your first place of work?", "Who was your first crush?", " " }));
        getContentPane().add(cmbQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 256, 511, 34));

        txtAns1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtAns1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 209, 511, 34));

        txtAns2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtAns2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 303, 511, 34));

        txtUid.setEditable(false);
        txtUid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txtUid, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 68, 511, 34));

        txtMail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 115, 511, 34));

        btnSubmit.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        btnSubmit.setText("Submit and Login");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 369, 202, 35));

        btnClr.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        btnClr.setText("Clear Fields");
        getContentPane().add(btnClr, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/hotel/management/free-light-blue-abstract-background-png-download-free-clip-art.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, -320, 970, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
         String email,q1,q2,a1,a2,uid;
         email=txtMail.getText();
         a1=txtAns1.getText();
         a2=txtAns2.getText();
         q1=cmbQ1.getSelectedItem().toString();
         q2=cmbQ2.getSelectedItem().toString();
         uid=txtUid.getText();
         Pattern p2=Pattern.compile("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[com]+$");
         Matcher mat2=p2.matcher(email);
          
         if(uid.isEmpty()||a1.isEmpty()||q1.isEmpty()||a2.isEmpty()||q2.isEmpty()||email.isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Please complete setting up security questions","Complete Signup",WARNING_MESSAGE);
         
         }
         else if(!mat2.matches()){
             JOptionPane.showMessageDialog(rootPane, "You have entered an invalid e-mail","Invalid entry",ERROR_MESSAGE);
         }
         else{
         DBConnect con=new DBConnect();
        Connection c=con.connect();
        try{
            Statement s1=c.createStatement();
            int co=s1.executeUpdate("update signup set email='"+email+"',question1='"+q1+"',answer1='"+a1+"',question2='"+q2+"',answer2='"+a2+"' where uid='"+uid+"'");
            if(co==1){
                int x=JOptionPane.showConfirmDialog(rootPane, "Confirm Your Backup Questions and Log In","Confirm",OK_CANCEL_OPTION,WARNING_MESSAGE);
                  if(x==0){
                      this.setVisible(false);
                      Login l=new Login();
                      l.setVisible(true);
                  }      
            }
        }
        catch(SQLException e){
            System.out.println(e.getMessage());
        }
         }
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PwdBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PwdBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PwdBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PwdBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PwdBackup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cmbQ1;
    private javax.swing.JComboBox cmbQ2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAns1;
    private javax.swing.JTextField txtAns2;
    private javax.swing.JTextField txtMail;
    public static javax.swing.JTextField txtUid;
    // End of variables declaration//GEN-END:variables
}
