/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.project.hotel.management;



import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.Random;

import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;


/**
 *
 * @author Cpt.coldblood
 */
public class ResetMail extends javax.swing.JFrame {

   

    /**
     * Creates new form ResetPwd
     */
    public ResetMail() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ic.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUid = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        lblsq = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recover password");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setText("Forgot Your Password?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 13, 324, 32));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Send recovery code to your email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 180, 302, 32));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Is this Your Email?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 230, 162, 27));
        getContentPane().add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 231, 268, 27));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Enter User Id to Locate your account");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 75, 286, 32));
        getContentPane().add(txtUid, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 120, 195, 53));

        btnSearch.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 150, -1, -1));

        btnSend.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        btnSend.setText("Confirm & Send Code");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 271, 193, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Insert the Recovery Code Below");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 325, 258, 29));
        getContentPane().add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 361, 173, 34));

        lblsq.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblsq.setForeground(new java.awt.Color(0, 0, 255));
        lblsq.setText("Do not Have an email? Login Using Security Questions");
        lblsq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsqMouseClicked(evt);
            }
        });
        getContentPane().add(lblsq, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 348, -1));

        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLogin.setText("Back To Login Page");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, -1, 41));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 139, 41));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/hotel/management/grain-798296_960_720.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void sendMail(String recepient,String textcode) throws MessagingException {
      Properties prop = new Properties();
       prop.put("mail.smtp.auth", "true");
       prop.put("mail.smtp.starttls.enable", "true");
       prop.put("mail.smtp.host", "smtp.gmail.com");
       prop.put("mail.smtp.ssl.trust", "smtp.gmail.com");
       prop.put("mail.smtp.port", "587");
       String adminemail="recoverhoteluserpwrd@gmail.com";
       String adminpassword="cojava191p@nibm";
        Authenticator auth= new Authenticator() {
          @Override
          protected PasswordAuthentication getPasswordAuthentication() {
             return new PasswordAuthentication(adminemail, adminpassword);
          }
                
        };
       Session new1=Session.getInstance(prop, auth);
        
        Message message = PrepareMessage(new1,adminemail,recepient,textcode);
        Transport.send(message);
        JOptionPane.showMessageDialog(null,"Code sent Successfully","Success", INFORMATION_MESSAGE);
    

        
      }
     private static Message PrepareMessage(Session new1, String adminemail,String recepient,String textcode) {
        try {
            Message message = new MimeMessage(new1);
            message.setFrom(new InternetAddress(adminemail));
            message.setRecipient(Message.RecipientType.TO, new InternetAddress(recepient));
            message.setSubject("Reset Password");
            message.setText(textcode);
            return message;
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        return null;
    }
    
    
 int x;String y;
            
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String id=txtUid.getText();
        
         DBConnect con1=new DBConnect();
          con1.connect();
        
        try {
            Statement s1=con1.connect().createStatement();
            ResultSet rs1=s1.executeQuery("select uid,email from signup where uid='"+id+"'");
            while(rs1.next()){
                txtMail.setText(rs1.getString(2));
            }
            }
        catch(SQLException e){
            System.out.print(e.getMessage());
        }
        if(txtMail.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "User ID Not Found", "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
       if(txtMail.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"NO EMAIL PROVIDED!!!","ERROR",ERROR_MESSAGE);
       }
        else {        String code[]= new String[10];
        Random rd = new Random();
        
        for(int i=0;i<8;i++){
            code[i]=Integer.toString(rd.nextInt(10));
        }
        y=code[0]+code[1]+code[2]+code[3]+code[4]+code[5]+code[6]+code[7];
        String textcode = "Your Password Recovery Code is"+y+"\nEnter This code in the textbox to reset your password";
        String recepient=txtMail.getText(); 
        try {
            sendMail(recepient,textcode);
        } catch (MessagingException ex) {
            System.out.println(ex.getMessage());
        }
       
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String gotcode=txtCode.getText();
       String a=txtUid.getText();
       if(gotcode.equals(y)){
           Newpwd np=new Newpwd();
           Newpwd.txtUid.setText(a);
           np.setVisible(true);
           this.setVisible(false);
       }
       else{
           JOptionPane.showMessageDialog(rootPane, "Wrong Code Entered.Please check again", "Error", ERROR_MESSAGE);
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       int x=JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to Quit\n your data will not be saved!", "Confirm", WARNING_MESSAGE);
        if(x==0){
            this.setVisible(false);
        
       Login l= new Login();
       l.setVisible(true);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblsqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsqMouseClicked
        this.setVisible(false);
        ResetQuestions rq=new ResetQuestions();
        rq.setVisible(true);
        ResetQuestions.txtUid.setText(txtUid.getText());
    }//GEN-LAST:event_lblsqMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetMail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblsq;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtMail;
    public static javax.swing.JTextField txtUid;
    // End of variables declaration//GEN-END:variables
}
