/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.project.hotel.management;

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_CANCEL_OPTION;

/**
 *
 * @author Cpt.coldblood
 */
public class Room extends javax.swing.JFrame {

    /**
     * Creates new form Room
     */
    public Room() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ic.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        txtCharge = new javax.swing.JFormattedTextField();
        txtRNo = new javax.swing.JTextField();
        cmbType = new javax.swing.JComboBox();
        chkBrkfst = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        chkLunch = new javax.swing.JCheckBox();
        chkDinner = new javax.swing.JCheckBox();
        chkCleaning = new javax.swing.JCheckBox();
        chkWifi = new javax.swing.JCheckBox();
        chkBar = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        btnRegRoom = new javax.swing.JButton();
        btnClr = new javax.swing.JButton();
        btnSrch = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        lblLogout = new javax.swing.JLabel();
        lblMain = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Room Management");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Room Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 11, 266, 58));

        jLabel2.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        jLabel2.setText("Room Type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 169, 145, 51));

        jLabel3.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        jLabel3.setText("Service Package");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 238, 145, 51));

        jLabel4.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        jLabel4.setText("Room No.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 100, 145, 51));

        jLabel5.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        jLabel5.setText("Charges Per Day");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 355, 145, 51));

        jLabel6.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        jLabel6.setText("Room Description");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 424, 145, 51));

        txtDesc.setColumns(20);
        txtDesc.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 424, 390, -1));

        txtCharge.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCharge.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCharge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChargeKeyPressed(evt);
            }
        });
        getContentPane().add(txtCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 280, 51));

        txtRNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txtRNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 390, 51));

        cmbType.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Couple", "Group", "Family" }));
        getContentPane().add(cmbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 169, 390, 36));

        chkBrkfst.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        chkBrkfst.setForeground(new java.awt.Color(0, 153, 0));
        chkBrkfst.setText("Breakfast");
        getContentPane().add(chkBrkfst, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Food");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 81, 24));

        chkLunch.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        chkLunch.setForeground(new java.awt.Color(0, 153, 0));
        chkLunch.setText("Lunch");
        getContentPane().add(chkLunch, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        chkDinner.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        chkDinner.setForeground(new java.awt.Color(0, 153, 0));
        chkDinner.setText("Dinner");
        getContentPane().add(chkDinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 81, -1));

        chkCleaning.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        chkCleaning.setForeground(new java.awt.Color(0, 153, 0));
        chkCleaning.setText("Cleaning");
        getContentPane().add(chkCleaning, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        chkWifi.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        chkWifi.setForeground(new java.awt.Color(0, 153, 0));
        chkWifi.setText("Wifi");
        getContentPane().add(chkWifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        chkBar.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        chkBar.setForeground(new java.awt.Color(0, 153, 0));
        chkBar.setText("Bar");
        getContentPane().add(chkBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 65, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Sans Unicode", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Miscellaneous");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, 24));

        btnRegRoom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegRoom.setText("Register Room");
        btnRegRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 139, 49));

        btnClr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnClr.setText("Clear");
        btnClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrActionPerformed(evt);
            }
        });
        getContentPane().add(btnClr, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 105, 49));

        btnSrch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSrch.setText("Search");
        btnSrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSrchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSrch, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, 105, 49));

        btnDel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDel.setText("Delelte");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        getContentPane().add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 105, 49));

        lblLogout.setForeground(new java.awt.Color(0, 0, 255));
        lblLogout.setText("LogOut");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 59, -1));

        lblMain.setForeground(new java.awt.Color(0, 0, 255));
        lblMain.setText("MainMenu");
        lblMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMainMouseClicked(evt);
            }
        });
        getContentPane().add(lblMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 59, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("LKR");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 90, 50));

        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/hotel/management/room-interior-background.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegRoomActionPerformed
       String Rno,Rtype,desc,breakfast="yes",lunch="yes",dinner="yes",cleaning="yes",wifi="yes",bar="yes";float charge;
       Rno=txtRNo.getText();
       Rtype=cmbType.getSelectedItem().toString();
       charge=Float.parseFloat(txtCharge.getText());
       desc=txtDesc.getText();
       if(!chkBrkfst.isSelected()){
       breakfast="no";    
       }
       if(!chkLunch.isSelected()){
           lunch="no";
       }
       if(!chkDinner.isSelected()){
           dinner="no";
       }
       if(!chkCleaning.isSelected()){
           cleaning="no";
       }
       if(!chkWifi.isSelected()){
           wifi="no";
       }
       if(!chkBar.isSelected()){
           bar="no";
       }
       boolean chg;
     if(charge==0){
         chg=true;
     }
     else{
         chg=false;
     }
       if(Rno.isEmpty()||desc.isEmpty()||chg){
          JOptionPane.showMessageDialog(rootPane,"Please Complete All the fields"); 
           
       }
       else{
       DBConnect con=new DBConnect();
       con.connect();
       try{
           Statement s1=con.connect().createStatement();
           int co=s1.executeUpdate("insert into rooms values('"+Rno+"','"+Rtype+"','"+breakfast+"','"+lunch+"','"+dinner+"','"+cleaning+"','"+wifi+"','"+bar+"','"+charge+"','"+desc+"')");
           
               if(co==1){
                   JOptionPane.showConfirmDialog(rootPane, "Added to database","succesful", OK_CANCEL_OPTION, INFORMATION_MESSAGE);
               } 
               else{JOptionPane.showMessageDialog(rootPane, "failed");}
           
       }
       catch(SQLException e)
       {System.out.println(e.getMessage());
           
       }
       txtRNo.setText(null);
       cmbType.setSelectedIndex(0);
       txtCharge.setText(null);
       txtDesc.setText(null);
       chkBar.setSelected(false);
       chkBrkfst.setSelected(false);
       chkLunch.setSelected(false);
       chkDinner.setSelected(false);
      chkCleaning.setSelected(false); 
       chkWifi.setSelected(false);
       }
    }//GEN-LAST:event_btnRegRoomActionPerformed

    private void btnClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrActionPerformed
        txtRNo.setText(null);
       cmbType.setSelectedIndex(0);
       txtCharge.setText(null);
       txtDesc.setText(null);
       chkBar.setSelected(false);
       chkBrkfst.setSelected(false);
       chkLunch.setSelected(false);
       chkDinner.setSelected(false);
      chkCleaning.setSelected(false); 
       chkWifi.setSelected(false);
    }//GEN-LAST:event_btnClrActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
         String rno=JOptionPane.showInputDialog(rootPane, "Enter the Room Number to delete data","Delete Room Data",WARNING_MESSAGE);
        
        DBConnect con1=new DBConnect();
      
          con1.connect();
        try {
            Statement s1=con1.connect().createStatement();
            int co=s1.executeUpdate("delete from rooms where rno='"+rno+"'");
            if(co==1){
                JOptionPane.showMessageDialog(rootPane, "Deleted");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Could not delete.Try Again after checking the room Number","Error",ERROR_MESSAGE);
            }
        }
        catch(SQLException e){
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnSrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSrchActionPerformed
         String search=JOptionPane.showInputDialog(null,"Enter the Room number of the employee to search","Search");
         DBConnect con1=new DBConnect();
          con1.connect();
        
        try {
            Statement s1=con1.connect().createStatement();
            ResultSet rs1=s1.executeQuery("select * from rooms where rno='"+search+"'");
            while(rs1.next()){
              txtRNo.setText(rs1.getString(1));
              cmbType.setSelectedItem(rs1.getString(2));
              txtCharge.setText(rs1.getString(9));
              txtDesc.setText(rs1.getString(10));  
              String x="yes";
              if(x.equalsIgnoreCase(rs1.getString(3))){
                  chkBrkfst.setSelected(true);
              }  
               if(x.equalsIgnoreCase(rs1.getString(4))){
                  chkLunch.setSelected(true);
              }  
                if(x.equalsIgnoreCase(rs1.getString(5))){
                  chkDinner.setSelected(true);
              }  
                if(x.equalsIgnoreCase(rs1.getString(6))){
                  chkCleaning.setSelected(true);
              }  
                 if(x.equalsIgnoreCase(rs1.getString(7))){
                  chkWifi.setSelected(true);
              }  
                 if(x.equalsIgnoreCase(rs1.getString(8))){
                  chkBar.setSelected(true);
              }  
              
              
              
            }
            }
         catch(SQLException e){
            System.out.print(e.getMessage());
        }
        if(txtRNo.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Entry Not Found", "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSrchActionPerformed

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        int x=JOptionPane.showConfirmDialog(rootPane, "Are You Sure You Want to log out", "LOG OUT", YES_NO_CANCEL_OPTION, WARNING_MESSAGE);
       if (x==0){
           this.setVisible(false);
           Login login=new Login();login.setVisible(true);this.setVisible(false);
       }
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainMouseClicked
         Mainmenu n=new Mainmenu();
        n.setVisible(true);
    }//GEN-LAST:event_lblMainMouseClicked

    private void txtChargeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChargeKeyPressed
        char c=evt.getKeyChar();
        char[] x=".".toCharArray();
        if(Character.isLetter(c)||Character.isWhitespace(c)||!Character.isDefined(x[0])){
            txtCharge.setEditable(false);
        }
        else{
             txtCharge.setEditable(true);
        }
    }//GEN-LAST:event_txtChargeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnRegRoom;
    private javax.swing.JButton btnSrch;
    private javax.swing.JCheckBox chkBar;
    private javax.swing.JCheckBox chkBrkfst;
    private javax.swing.JCheckBox chkCleaning;
    private javax.swing.JCheckBox chkDinner;
    private javax.swing.JCheckBox chkLunch;
    private javax.swing.JCheckBox chkWifi;
    private javax.swing.JComboBox cmbType;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblMain;
    private javax.swing.JFormattedTextField txtCharge;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtRNo;
    // End of variables declaration//GEN-END:variables
}
