/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.project.hotel.management;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;


/**
 *
 * @author Cpt.coldblood
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ic.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSid = new javax.swing.JTextField();
        txtUid = new javax.swing.JTextField();
        txtUname = new javax.swing.JTextField();
        txtPwd = new javax.swing.JPasswordField();
        txtCpwd = new javax.swing.JPasswordField();
        btnContinue = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnClr = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign up");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 282, 61));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel2.setText("UserName");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 200, 37));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 200, 37));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 200, 37));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel5.setText("Staff ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 200, 37));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel6.setText("User ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 200, 37));

        txtSid.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txtSid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 380, 60));

        txtUid.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txtUid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 257, 380, 50));

        txtUname.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnameActionPerformed(evt);
            }
        });
        txtUname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUnameKeyPressed(evt);
            }
        });
        getContentPane().add(txtUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 347, 380, 50));

        txtPwd.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        txtPwd.setToolTipText("Password must contain atleast 8 characters including Uppercase Letters,Lowercase Letters,Numbers & Symbols");
        txtPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPwdActionPerformed(evt);
            }
        });
        getContentPane().add(txtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 427, 380, 50));

        txtCpwd.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        getContentPane().add(txtCpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 380, 50));

        btnContinue.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnContinue.setText("Contine to SignUp");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, 261, 33));

        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLogin.setText("Go To Login Page");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 690, -1, 33));

        btnClr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClr.setText("Clear Fields");
        btnClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrActionPerformed(evt);
            }
        });
        getContentPane().add(btnClr, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 690, -1, 33));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/hotel/management/background-tumblr-vertical-8.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnameActionPerformed

    private void txtPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPwdActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        Login l=new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        String eno,uid,uname,pwd;
        eno=txtSid.getText();
        uid=txtUid.getText();
        uname=txtUname.getText();
        pwd=txtPwd.getText();
        String cpwd=txtCpwd.getText();
        if(eno.isEmpty()||uid.isEmpty()||uname.isEmpty()||pwd.isEmpty()||cpwd.isEmpty()){
            JOptionPane.showMessageDialog(null, "please Do not leave empty");
        }
        else if(ValidatePassword.checkPwd(pwd)==false||ValidatePassword.specialCheck(pwd)==false){
                       JOptionPane.showMessageDialog(null,"Password Must contain atleast 8 characters \nwith one or more of an uppercase letter,a lowercase letter,a number and symbol","Weak Password",JOptionPane.ERROR_MESSAGE);
                       txtPwd.setText(null);
                       txtCpwd.setText(null);
        }
        else if(!pwd.equals(cpwd)){
            JOptionPane.showMessageDialog(rootPane, "Paswords do not match.");
            txtPwd.setText(null);
            txtCpwd.setText(null);
        }
        else{
            DBConnect con=new DBConnect();
            Connection c=con.connect();
            try{
                Statement s1=c.createStatement();
                int co=s1.executeUpdate("insert into signup values('"+uid+"','"+eno+"','"+uname+"','"+pwd+"','','','','','')");
                if (co==1){
                    JOptionPane.showMessageDialog(rootPane, "Successful Entry");
                    PwdBackup b=new PwdBackup();
                    PwdBackup.txtUid.setText(uid);
                    b.setVisible(true);
                    this.setVisible(false);
                }
            }
            catch(SQLException e){
                System.out.print(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnContinueActionPerformed

    private void btnClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrActionPerformed
       txtCpwd.setText(null);
       txtPwd.setText(null);
       txtSid.setText(null);
       txtUid.setText(null);
       txtUname.setText(null);
    }//GEN-LAST:event_btnClrActionPerformed

    private void txtUnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnameKeyPressed
        char c=evt.getKeyChar();
           if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
               txtUname.setEditable(true);
           }
           else{txtUname.setEditable(false);
           
           }
    }//GEN-LAST:event_txtUnameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField txtCpwd;
    private javax.swing.JPasswordField txtPwd;
    public static javax.swing.JTextField txtSid;
    public static javax.swing.JTextField txtUid;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
