/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.project.hotel.management;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import java.text.*;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_CANCEL_OPTION;
import javax.swing.JTextField;
/**
 *
 * @author Cpt.coldblood
 */
public class Staff extends javax.swing.JFrame {

    /**
     * Creates new form Staff
     */
    public Staff() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ic.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSid = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        rdbMale = new javax.swing.JRadioButton();
        rdbFemale = new javax.swing.JRadioButton();
        txtPhone = new javax.swing.JTextField();
        txtSemail = new javax.swing.JTextField();
        cmbCentre = new javax.swing.JComboBox();
        txtSnic = new javax.swing.JTextField();
        dateDOB = new com.toedter.calendar.JDateChooser();
        lblLogout = new javax.swing.JLabel();
        lblMain = new javax.swing.JLabel();
        btnClr = new javax.swing.JButton();
        btnReg = new javax.swing.JButton();
        btnSrc = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel3.setText("Name");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff Management");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Staff Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 13, 385, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Employee ID Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 91, 170, 47));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Phone Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 416, 160, 47));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 481, 160, 47));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("NIC No.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 546, 160, 47));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Work Centre");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 221, 160, 47));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 156, 160, 47));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Date of Birth");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 286, 160, 47));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Gender");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 351, 160, 47));

        txtSid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtSid, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 91, 317, 47));

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 156, 317, 47));

        buttonGroup1.add(rdbMale);
        rdbMale.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        rdbMale.setText("Male");
        rdbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMaleActionPerformed(evt);
            }
        });
        getContentPane().add(rdbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 363, 80, -1));

        buttonGroup1.add(rdbFemale);
        rdbFemale.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        rdbFemale.setText("Female");
        getContentPane().add(rdbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 363, -1, -1));

        txtPhone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 416, 317, 47));

        txtSemail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtSemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 481, 317, 47));

        cmbCentre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbCentre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Management", "Reception", "Kitchen & Waiting", "Security & Maintenance" }));
        getContentPane().add(cmbCentre, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 221, 317, 47));

        txtSnic.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtSnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 546, 317, 47));

        dateDOB.setDateFormatString("yyyy-M-dd");
        dateDOB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(dateDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 292, 320, 40));

        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(204, 0, 0));
        lblLogout.setText("Log Out");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 90, 20));

        lblMain.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMain.setForeground(new java.awt.Color(204, 0, 0));
        lblMain.setText("Main Menu");
        lblMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMainMouseClicked(evt);
            }
        });
        getContentPane().add(lblMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 90, 20));

        btnClr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClr.setText("Clear");
        btnClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrActionPerformed(evt);
            }
        });
        getContentPane().add(btnClr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 640, 120, 40));

        btnReg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnReg.setText("Register");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });
        getContentPane().add(btnReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 640, 120, 40));

        btnSrc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSrc.setText("Search");
        btnSrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSrcActionPerformed(evt);
            }
        });
        getContentPane().add(btnSrc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, 130, 40));

        btnDel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        getContentPane().add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 120, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/hotel/management/depositphotos_114222222-stock-photo-cool-gradient-background.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemailActionPerformed

    private void rdbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbMaleActionPerformed

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
    String eno,ename,ecentre,email,nic,gender,dob,phone;
    eno=txtSid.getText();
    ename=txtName.getText();
    ecentre=cmbCentre.getSelectedItem().toString();
    phone=txtPhone.getText();
    email=txtSemail.getText();
    
    nic=txtSnic.getText();
    
    dob=((JTextField)dateDOB.getDateEditor().getUiComponent()).getText();
    
    
    
    if(rdbMale.isSelected()){
        gender="Male";
       
    }
    else{
        gender="Female";
    }
    Pattern p=Pattern.compile("^[0-9]{10}$");
          Matcher mat=p.matcher(phone);
          Pattern p2=Pattern.compile("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[com]+$");
          Matcher mat2=p2.matcher(email);
          Pattern p3 =Pattern.compile("^[a-zA-Z]+$");
          Matcher mat3=p3.matcher(ename);
    if(eno.isEmpty()||ename.isEmpty()||ecentre.isEmpty()||phone.isEmpty()||email.isEmpty()||nic.isEmpty()||gender.isEmpty()||dob.isEmpty()){
                    JOptionPane.showMessageDialog(rootPane, "Please Fill out All the details","Empty Fields",WARNING_MESSAGE);
    }
     else if(!mat.matches()){
            JOptionPane.showMessageDialog(rootPane, "You have entered an invalid telephone number","Invalid entry",ERROR_MESSAGE);
       }
           else if(!mat2.matches()){
               JOptionPane.showMessageDialog(rootPane, "You have entered an invalid e-mail","Invalid entry",ERROR_MESSAGE);
           }
             else if(!mat3.matches()){
               JOptionPane.showMessageDialog(rootPane, "Please donot use any symbols or numbers in your name","Invalid entry",ERROR_MESSAGE);
           }
    else{
    DBConnect con=new DBConnect();
    Connection c1=con.connect();
    try{
        Statement s1=c1.createStatement();
        int co=s1.executeUpdate("insert into staff values('"+eno+"','"+ename+"','"+ecentre+"','"+dob+"','"+gender+"','"+phone+"','"+email+"','"+nic+"')");
        if(co==1){
            JOptionPane.showMessageDialog(null, "Successful Entry");
        }
    }
    catch(SQLException e){
        System.out.print(e.getMessage());
    }
    
    
    txtSid.setText(null);
    txtName.setText(null);
    txtPhone.setText(null);
    txtSemail.setText(null);
    txtSnic.setText(null);
    buttonGroup1.clearSelection();
    cmbCentre.setSelectedIndex(0);
    dateDOB.setDate(null);
            }
    }//GEN-LAST:event_btnRegActionPerformed

    private void btnClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrActionPerformed
        txtSid.setText(null);
    txtName.setText(null);
    txtPhone.setText(null);
    txtSemail.setText(null);
    txtSnic.setText(null);
    buttonGroup1.clearSelection();
    cmbCentre.setSelectedIndex(0);dateDOB.setDate(null);
    }//GEN-LAST:event_btnClrActionPerformed

    private void btnSrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSrcActionPerformed
       String search=JOptionPane.showInputDialog(null,"Enter the Employee ID number of the employee to search","Search");
         DBConnect con1=new DBConnect();
          con1.connect();
        
        try {
            Statement s1=con1.connect().createStatement();
            ResultSet rs1=s1.executeQuery("select * from staff where eno='"+search+"'");
            while(rs1.next()){
                
                txtSid.setText(rs1.getString(1));
                txtName.setText(rs1.getString(2));
                cmbCentre.setSelectedItem(rs1.getString(3));
                dateDOB.setDate(rs1.getDate(4));
                txtPhone.setText(rs1.getString(6));
                txtSemail.setText(rs1.getString(7));
                txtSnic.setText(rs1.getString(8));
                if(rs1.getString(5).equals("Male")){
                    rdbMale.setSelected(true);
                    
                }
                else{
                    rdbFemale.setSelected(true);
                    
                }
            
            
            }
            }
        catch(SQLException e){
            System.out.println(e.getMessage());
        }
         if(txtSid.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Entry Not Found", "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSrcActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        String eno=JOptionPane.showInputDialog(rootPane, "Enter the Staff ID to delete data","Delete Employee Data",WARNING_MESSAGE);
        
        DBConnect con1=new DBConnect();
      
          con1.connect();
        try {
            Statement s1=con1.connect().createStatement();
            int co=s1.executeUpdate("delete from staff where eno='"+eno+"'");
            if(co==1){
                JOptionPane.showMessageDialog(rootPane, "Deleted");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Could not delete.Try Again after checking the Staff ID Number","Error",ERROR_MESSAGE);
            }
        }
        catch(SQLException e){
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void lblMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainMouseClicked
            Mainmenu m= new Mainmenu();
            m.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_lblMainMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
             int x=JOptionPane.showConfirmDialog(rootPane, "Are You Sure You Want to log out", "LOG OUT", YES_NO_CANCEL_OPTION, WARNING_MESSAGE);
       if (x==0){
           Login login=new Login();login.setVisible(true);this.setVisible(false);
       }
    }//GEN-LAST:event_lblLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnReg;
    private javax.swing.JButton btnSrc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbCentre;
    private com.toedter.calendar.JDateChooser dateDOB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblMain;
    private javax.swing.JRadioButton rdbFemale;
    private javax.swing.JRadioButton rdbMale;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSemail;
    private javax.swing.JTextField txtSid;
    private javax.swing.JTextField txtSnic;
    // End of variables declaration//GEN-END:variables
}
