/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.project.hotel.management;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_CANCEL_OPTION;
import javax.swing.JTextField;

/**
 *
 * @author Cpt.coldblood
 */
public class Stores extends javax.swing.JFrame {

    /**
     * Creates new form Stores
     */
    public Stores() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ic.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtStockId = new javax.swing.JTextField();
        txtStckname = new javax.swing.JTextField();
        txtStckvalue = new javax.swing.JTextField();
        cmbStckCenter = new javax.swing.JComboBox();
        btnSrch = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        btnReg = new javax.swing.JButton();
        txtExp = new com.toedter.calendar.JDateChooser();
        lblMain = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        btnClr = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Store Management");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Store Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 330, 46));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Stock ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 66, 190, 30));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Stock Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 114, 190, 30));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Stock Center");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 162, 190, 30));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Stock Description");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 190, 30));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("Stock Value");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 170, 30));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("Expiration Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 170, 34));
        getContentPane().add(txtStockId, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 66, 391, 30));

        txtStckname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStcknameKeyPressed(evt);
            }
        });
        getContentPane().add(txtStckname, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 114, 391, 30));

        txtStckvalue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStckvalueKeyPressed(evt);
            }
        });
        getContentPane().add(txtStckvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 213, 391, 32));

        cmbStckCenter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbStckCenter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Management", "Reception", "Kitchen", "Security & Maintenance" }));
        getContentPane().add(cmbStckCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 164, 390, 30));

        btnSrch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSrch.setText("Search");
        btnSrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSrchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSrch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 93, 40));

        btnRemove.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, 40));

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 380, -1));

        btnReg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnReg.setText("Register");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });
        getContentPane().add(btnReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 110, 60));

        txtExp.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txtExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 380, 30));

        lblMain.setText("Main Menu");
        lblMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMainMouseClicked(evt);
            }
        });
        getContentPane().add(lblMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 70, 20));

        lblLogout.setText("Log Out");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 70, 20));

        btnClr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClr.setText("Clear");
        btnClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrActionPerformed(evt);
            }
        });
        getContentPane().add(btnClr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/hotel/management/bigstock-a-surplus-or-oversupply-of-pro-38532283-768x7291496231364.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 700, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        String stid,stname,stcenter,stdesc,stexp;float stvalue;
        stid=txtStockId.getText();
        stname=txtStckname.getText();
        stcenter=cmbStckCenter.getSelectedItem().toString();
        stdesc=txtDesc.getText();
        stexp=((JTextField)txtExp.getDateEditor().getUiComponent()).getText();
        stvalue=Float.parseFloat(txtStckvalue.getText());
        boolean chg=false;
        if(stvalue==0f){
            chg=true;
            
        }
        if(stid.isEmpty()||stname.isEmpty()||stcenter.isEmpty()||stdesc.isEmpty()||stexp.isEmpty()||chg){
            JOptionPane.showMessageDialog(rootPane, "Please Fill out All the details","Empty Fields",WARNING_MESSAGE);
        }
        
        else{ DBConnect con=new DBConnect();
        Connection c=con.connect();
        try{
            Statement s1=c.createStatement();
            int x=s1.executeUpdate("insert into store values('"+stid+"','"+stname+"','"+stcenter+"','"+stvalue+"','"+stdesc+"','"+stexp+"')");
            if(x==1){
                JOptionPane.showMessageDialog(null, "Successful Entry");
            }
        }
        catch(SQLException e){
            System.out.print(e.getMessage());
        }
        
        txtStockId.setText(null);
        txtStckname.setText(null);
        cmbStckCenter.setSelectedIndex(0);
        txtDesc.setText(null);
        txtExp.setDate(null);
        txtStckvalue.setText(null);
        }
    }//GEN-LAST:event_btnRegActionPerformed

    private void btnClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrActionPerformed
        txtStockId.setText(null);
        txtStckname.setText(null);
        cmbStckCenter.setSelectedIndex(0);
        txtDesc.setText(null);
        txtExp.setDate(null);
        txtStckvalue.setText(null);
    }//GEN-LAST:event_btnClrActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
String stoid=JOptionPane.showInputDialog(rootPane, "Enter the Staff ID to delete data","Delete Employee Data",WARNING_MESSAGE);
        
        DBConnect con1=new DBConnect();
      
          con1.connect();
        try {
            Statement s1=con1.connect().createStatement();
            int co=s1.executeUpdate("delete from store where stoid='"+stoid+"'");
            if(co==1){
                JOptionPane.showMessageDialog(rootPane, "Deleted");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Could not delete.Try Again after checking the Stock ID Number","Error",ERROR_MESSAGE);
            }
        }
        catch(SQLException e){
            System.out.print(e.getMessage());
        }       
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnSrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSrchActionPerformed
      String search=JOptionPane.showInputDialog(null,"Enter the stock ID number of the goods to search","Search");
         DBConnect con1=new DBConnect();
          con1.connect();
        
        try {
            Statement s1=con1.connect().createStatement();
            ResultSet rs1=s1.executeQuery("select * from store where stoid='"+search+"'");
            while(rs1.next()){
                
                txtStockId.setText(rs1.getString(1));
                txtStckname.setText(rs1.getString(2));
                cmbStckCenter.setSelectedItem(rs1.getString(3));
                txtExp.setDate(rs1.getDate(6));
                txtStckvalue.setText(rs1.getString(4));
                txtDesc.setText(rs1.getString(5));
               
                
            
            
            }
            }
        catch(SQLException e){
            System.out.println(e.getMessage());
        }
         if(txtStockId.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Entry Not Found", "Error", ERROR_MESSAGE);
        }
                                       
    }//GEN-LAST:event_btnSrchActionPerformed

    private void lblMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainMouseClicked
        this.setVisible(false);
        Mainmenu m = new Mainmenu();
        m.setVisible(true);
    }//GEN-LAST:event_lblMainMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        int x=JOptionPane.showConfirmDialog(rootPane, "Are You Sure You Want to log out", "LOG OUT", YES_NO_CANCEL_OPTION, WARNING_MESSAGE);
       if (x==0){
           Login login=new Login();login.setVisible(true);this.setVisible(false);
       }
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void txtStcknameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStcknameKeyPressed
char c=evt.getKeyChar();
           if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
               txtStckname.setEditable(true);
           }
           else{txtStckname.setEditable(false);
           
           }
    }//GEN-LAST:event_txtStcknameKeyPressed

    private void txtStckvalueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStckvalueKeyPressed
     char c=evt.getKeyChar();
        char[] x=".".toCharArray();
        if(Character.isDigit(c)||Character.isDefined(x[0])){
            txtStckvalue.setEditable(true);
        }
        else{
             txtStckvalue.setEditable(false);
        }
    }//GEN-LAST:event_txtStckvalueKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnReg;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSrch;
    private javax.swing.JComboBox cmbStckCenter;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblMain;
    private javax.swing.JTextArea txtDesc;
    private com.toedter.calendar.JDateChooser txtExp;
    private javax.swing.JTextField txtStckname;
    private javax.swing.JTextField txtStckvalue;
    private javax.swing.JTextField txtStockId;
    // End of variables declaration//GEN-END:variables
}
